services:
  - type: web
    name: shadowchain-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
    disk:
      name: blockchain-data
      mountPath: /data
      sizeGB: 1

